name: Deploy CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - name: Restart pm2
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /opt/atlantica
            git pull
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm i
            npm run build
            pm2 restart all
